blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='blog-home'),
    path('blog/<int:index>/', views.view_post, name='blog-view-post'),
    path('about/', views.about, name='blog-about'),
]

contests/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='contests-home'),
    path('<int:index>/confirm/', views.confirm, name='contests-confirm'),
    path('<int:index>/submit/', views.submit, name='contests-submit'),
    path('<int:index>/semiarena/', views.semiarena, name='contests-semiarena'),
    path('<int:index>/arena/', views.arena, name='contests-arena'),
    path('<int:index>/scoreboard/', views.scoreboard, name='contests-scoreboard'),
    path('<int:index>/preview/', views.preview, name='contests-preview'),
]

semicolon_src/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('contests/', include('contests.urls')),
    path('problemset/', include('problemset.urls')),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
]

contests/models.py
from django.db import models
from django.utils import timezone
from problemset.models import Problem

CONTEST_FORMATS = (
    ('AMC8', 'AMC8'),
    ('AMC10', 'AMC10'),
    ('AIME', 'AIME'),
    ('Semicolon', 'Semicolon')
)

class Contest(models.Model):
    name = models.CharField(max_length=100)
    start_time = models.DateTimeField(default=timezone.now)
    end_time = models.DateTimeField(default=timezone.now)
    visible = models.BooleanField(default=False)
    start_time_url = models.URLField(default="")
    end_time_url = models.URLField(default="")
    announcement_link = models.URLField(default="")
    time_limit = models.IntegerField(default=0)
    has_solutions = models.BooleanField(default=False)
    solutions_url = models.URLField(default="")
    contest_format = models.CharField(max_length=9, choices=CONTEST_FORMATS, default='Semicolon')
    form_user_submit_solutions = models.BooleanField(default=False)
    form_link = models.URLField(default="")
    
    def __str__(self):
        return self.name

class ContestProblem(models.Model):
    contest = models.ForeignKey(Contest, on_delete=models.CASCADE)
    problem = models.ForeignKey(Problem, on_delete=models.CASCADE)
    value = models.IntegerField(default=0)

    def __str__(self):
        return f"Contest: {self.contest.name}, Problem: {self.problem.name}"

class Registration(models.Model):
    user_id = models.IntegerField()
    contest_id = models.IntegerField()
    time_joined = models.DateTimeField(default=timezone.now)
    total_points = models.DecimalField(default=0, max_digits=10, decimal_places=1)
    total_penalty = models.IntegerField(default=0)
    confirmed_honest = models.BooleanField(default=False)
    verify_end_time = models.DateTimeField(default=timezone.now)

contests/forms.py
from django import forms

class RegisterForm(forms.Form):
    agree = forms.BooleanField(label="I agree to follow the rules")

class SubmitForm(forms.Form):
    agree = forms.BooleanField(label="I agreed that I followed the rules:")

class ProblemForm(forms.Form):
    answer = forms.IntegerField(label='Your answer (should be an integer)')
    problem_id = forms.IntegerField(label='', widget=forms.NumberInput(attrs={'class': 'problemId'}))

class AIMEProblemForm(forms.Form):
    answer = forms.IntegerField(label='Your answer (should be an integer)', widget=forms.NumberInput(attrs={'autocomplete': 'off'}))
    problem_id = forms.IntegerField(label='', widget=forms.NumberInput(attrs={'class': 'problemId'}))

class MultipleChoiceForm(forms.Form):
    ANSWER_CHOICES = [
        ('A', 'A'),
        ('B', 'B'),
        ('C', 'C'),
        ('D', 'D'),
        ('E', 'E'),
        ('Blank', 'Blank')
    ]
    answer = forms.ChoiceField(label='Answer', widget=forms.RadioSelect(attrs={'class': 'answerForm'}), choices=ANSWER_CHOICES)
    problem_id = forms.IntegerField(label='', widget=forms.NumberInput(attrs={'class': 'problemId'}))

contests/views.py
import datetime
from decimal import Decimal
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.views.decorators.cache import never_cache
from django.utils import timezone
from .models import Contest, ContestProblem, Registration
from .forms import RegisterForm, ProblemForm, MultipleChoiceForm, AIMEProblemForm, SubmitForm
import math
from problemset.models import Submission

# Create your views here.

def home(request):
    contests = Contest.objects.all().order_by('-id')
    visible_contests = []
    for contest in contests:
        contest.joined = False

        user_registration = Registration.objects.filter(
            user_id=request.user.id,
            contest_id=contest.id
        )
        if(len(user_registration) > 0):
            contest.joined = True
            time_diff = datetime.timedelta(minutes=contest.time_limit)
            contest.user_end_time = user_registration[0].time_joined + time_diff
            if contest.user_end_time > contest.end_time:
                contest.user_end_time = contest.end_time
            if timezone.now() <= contest.user_end_time and not user_registration[0].confirmed_honest:
                contest.running = True
            if timezone.now() < user_registration[0].verify_end_time and not user_registration[0].confirmed_honest:
                contest.needs_to_submit = True
                contest.submit_end_time = user_registration[0].verify_end_time

        if timezone.now() > contest.end_time:
            contest.ended = True
        elif timezone.now() >= contest.start_time:
            contest.started = True
            if(contest.visible):
                messages.info(request, f"{contest.name} is in progress!")

        if(contest.visible):
            visible_contests.append(contest)

    paginator = Paginator(visible_contests, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'current_server_time': math.floor(timezone.now().timestamp())
    }
    return render(request, 'contests/home.html', context)

@never_cache
def confirm(request, index):
    contest = Contest.objects.get(pk=index)
    if not contest.visible:
        return redirect('contests-home')
        
    if timezone.now() > contest.end_time:
        messages.error(request, f"You cannot take {contest.name} officially anymore.")
        return redirect('contests-home')

    if not request.user.is_authenticated:
        messages.error(request, "Please log in before joining the contest!")
        return redirect(f'/login/?next={request.path}')
    
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            agreed = form.cleaned_data.get('agree')

            if(agreed):
                new_user_registration = Registration(
                    user_id=request.user.id,
                    contest_id = contest.id
                )
                new_user_registration.save()
                messages.success(request, f"You have joined {contest.name}!")
                if(contest.contest_format == 'Semicolon'):
                    return redirect(f'/contests/{index}/semiarena/')
                else:
                    return redirect(f'/contests/{index}/arena/')

    else:
        form = RegisterForm()

    user_registration = Registration.objects.filter(
        user_id=request.user.id,
        contest_id=index
    )
    if(len(user_registration) > 0):
        messages.success(request, f"You already have joined this contest!")
        if(contest.contest_format == 'Semicolon'):
            return redirect(f'/contests/{index}/semiarena/')
        else:
            return redirect(f'/contests/{index}/arena')

    context = {
        'contest': contest,
        'form': form,
        'current_server_time': math.floor(timezone.now().timestamp())
    }
    return render(request, 'contests/confirm.html', context)

@never_cache
def submit(request, index):
    contest = Contest.objects.get(pk=index)
    user_registration = Registration.objects.filter(
        contest_id=index,
        user_id=request.user.id
    )
    if(len(user_registration) == 0):
        messages.error(request, f"You can't submit because you didn't register")
        return redirect('contests-home')
    if timezone.now() > user_registration[0].verify_end_time or user_registration[0].confirmed_honest:
        messages.error(request, f"You cannot submit {contest.name} anymore.")
        return redirect('contests-home')

    if not request.user.is_authenticated:
        messages.error(request, "Please log in before submitting the contest!")
        return redirect(f'/login/?next={request.path}')
    
    if request.method == 'POST':
        form = SubmitForm(request.POST)
        if form.is_valid():
            agreed = form.cleaned_data.get('agree')

            if(agreed):
                user_registration[0].confirmed_honest = True
                user_registration[0].save()
                messages.success(request, f"You have successfully submitted {contest.name}!")
                if(contest.contest_format == 'Semicolon'):
                    return redirect(f'/contests/{index}/semiarena/')
                else:
                    return redirect(f'/contests/{index}/arena/')

    else:
        form = SubmitForm()

    context = {
        'contest': contest,
        'form': form,
        'user_registration': user_registration[0],
        'current_server_time': math.floor(timezone.now().timestamp())
    }
    return render(request, 'contests/submit.html', context)

@never_cache
def semiarena(request, index):
    contest = Contest.objects.get(pk=index)
    user_registration = Registration.objects.filter(
        user_id=request.user.id,
        contest_id=index
    )
    contest_problems = ContestProblem.objects.filter(
        contest=contest
    ).order_by('id')

    if not contest.visible:
        return redirect('contests-home')

    if(contest.contest_format != 'Semicolon'):
        messages.error(request, "You can't use this arena for this type of contest!")
        return redirect('/contests/')

    if request.method == 'POST':
        form = ProblemForm(request.POST)
        redirect_url = '/contests/' + str(index) + '/semiarena/'
        if form.is_valid():
            problem_id = int(form.cleaned_data.get('problem_id'))
            problem = contest_problems[problem_id].problem
            user_answer = form.cleaned_data.get('answer')
            redirect_url += '#' + str(problem_id + 1)

            user_submissions = Submission.objects.filter(
                user_id=request.user.id,
                problem_id=problem.id
            )
            problem_solved = (user_answer == problem.correct_answer)
            
            contest_running = False
            time_diff = datetime.timedelta(minutes=contest.time_limit)
            if(len(user_registration) > 0):
                user_end_time = user_registration[0].time_joined + time_diff
                if user_end_time > contest.end_time:
                    user_end_time = contest.end_time
                if timezone.now() <= user_end_time:
                    contest_running = True

            submissions_remaining = 5
            if(contest_running and len(user_submissions) > 0):
                submissions_remaining = 5 - user_submissions[0].wrong_submissions_in_contest

            if(submissions_remaining == 0):
                pass
            elif(problem_solved):
                messages.success(request, f"Your answer {user_answer} for problem {problem_id + 1} is correct!")
            else:
                if(contest_running):
                    messages.error(request, f"Your answer {user_answer} for problem {problem_id + 1} is wrong! You have {submissions_remaining - 1} submissions left.")
                else:
                    messages.error(request, f"Your answer {user_answer} for problem {problem_id + 1} is wrong!")
            
            penalty_diff = 0
            time_solved_in_contest = 0
            wrong_submissions_diff = 0
            solved_in_contest = False
            if(contest_running):
                if(len(user_submissions) > 0 and user_submissions[0].wrong_submissions_in_contest == 5):
                    problem_solved = False
                    messages.error(request, f"You have already made 5 submissions to {problem_id + 1} and cannot make anymore!")
                elif(problem_solved):
                    solved_in_contest = True
                    time_since_start = timezone.now() - user_registration[0].time_joined
                    penalty_diff = int(math.floor(time_since_start.seconds / 60))
                    time_solved_in_contest = int(math.floor(time_since_start.seconds / 60))
                    prev_penalty = 0
                    if(len(user_submissions) > 0):
                        prev_penalty = user_submissions[0].penalty
                    user_registration[0].total_penalty += prev_penalty + penalty_diff
                    user_registration[0].total_points += Decimal(contest_problems[problem_id].value)
                    user_registration[0].save()
                else:
                    penalty_diff = 10 # 10 point penalty for every wrong submission
                    wrong_submissions_diff = 1

            if(len(user_submissions) == 0):
                new_user_submission = Submission(
                    user_id=request.user.id,
                    problem_id=problem.id,
                    problem_solved=problem_solved,
                    solved_in_contest=solved_in_contest,
                    penalty=penalty_diff,
                    time_solved_in_contest=time_solved_in_contest,

contests/templates/contests/confirm.html
{% load static %}
<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<title>(;) Register for: {{ contest.name }}</title>
		<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" />
	</head>
	<body>
		<div style="display: flex; justify-content: space-between; align-items: center;">
			<div>
				<h1>(;) Register for: {{ contest.name }}</h1>
			</div>
			<div style="float: right;">
				{% if user.is_authenticated %}
					<a href="{% url 'profile' %}">{{ user.username }}</a> |
					<a href="{% url 'logout' %}">Logout</a>
				{% else %}
					<a href="{% url 'login' %}">Login</a> |
					<a href="{% url 'register' %}">Register</a>
				{% endif %}
			</div>
		</div>
		<nav>
			<a href="{% url 'blog-home' %}">Home</a> |
			<a href="{% url 'contests-home' %}">Contests</a> |
			<a href="{% url 'problemset-home' %}">Problemset</a> |
			<a href="{% url 'blog-about' %}">About</a>
		</nav>
		{% if messages %}
			{% for message in messages %}
				<div class="alert alert-{{ message.tags }}">
					{{ message }}
				</div>
			{% endfor %}
		{% endif %}
		
		<h2>Joining contest: {{ contest.name }}</h2>
		<div class="alert alert-warning">

			<p style="font-size: 22px;"><b>
				By joining you agree to follow the rules and understand the contest format,
				both of which can be found in the
				<a href="{{ contest.announcement_link}}" style="color: blue;">
					the contest announcement</a>. Make sure to join
				our <a href="https://discord.gg/9deBe7WnEM" style="color: blue;">
					Discord server</a>
				to be aware of any announcements regarding technical issues.
				Note we WILL NOT post any clarifications of the problems DURING the contest.
			</b></p>

			<p style="font-size: 22px;"><b>
				Note that you will have to verify that you followed the rules by pressing the submit button
				in the contest arena. This will take you to a page to do so.
				{% if contest.form_user_submit_solutions %}
					You also MUST submit images of your work to a form (the link is also available on this 'submit' page).
				{% endif %}
				You will have 20 minutes after your contest attempt ends to do this task. You will be redirected to this page
				automatically when your contest attempt ends.
			</b><p>
			<p style="font-size: 22px;"><b>
				Contest ends at
				<a href="{{ contest.end_time_url }}" style="color: blue;">
					{{ contest.end_time }}</a> (UTC).
			</b></p>
			<p style="font-size: 22px;"><b>
				Contest ends in:
				<span class="timer" redirect="{% url 'contests-home' %}" current-server-time="{{ current_server_time }}" end-time="{{ contest.end_time|date:"U"}}"></span>
			</b></p>
			<p style="font-size: 22px;"><b>
				Time limit of your attempt:
				{{ contest.time_limit }} minutes
			</b></p>
			<p style="font-size: 22px;"><b>
				YOUR ATTEMPT WILL END WHEN THE CONTEST ENDS,
				EVEN IF YOU ARE UNDER THE TIME LIMIT.
			</b></p>
			<p style="font-size: 22px;"><b>
				It is recommended to open the arena in only one tab, use a tablet/laptop/desktop instead of a phone,
				and you can navigate back to the contest arena by going to the semicolon math website and clicking contests
				in case you close it by accident.
			</b></p>

		</div>

		<form method="POST">
			{% csrf_token %}
			{{ form.as_p }}
			<button type="submit">Join contest</button>
		</form>

		<script type="text/javascript" src="{% static 'js/timers.js' %}">
		</script>
  	</body>
</html>

contests/templates/contests/home.html
{% load static %}
<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<title>(;) Semicolon Math Contests</title>
		<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" />
	</head>
	<body>
		<div style="display: flex; justify-content: space-between; align-items: center;">
			<div>
				<h1>(;) Semicolon Math Contests</h1>
			</div>
			<div style="float: right;">
				{% if user.is_authenticated %}
					<a href="{% url 'profile' %}">{{ user.username }}</a> |
					<a href="{% url 'logout' %}">Logout</a>
				{% else %}
					<a href="{% url 'login' %}?next={{ request.path }}">Login</a> |
					<a href="{% url 'register' %}">Register</a>
				{% endif %}
			</div>
		</div>
		<nav>
			<a href="{% url 'blog-home' %}">Home</a> |
			<a href="#">Contests</a> |
			<a href="{% url 'problemset-home' %}">Problemset</a> |
			<a href="{% url 'blog-about' %}">About</a>
		</nav>
		{% if messages %}
			{% for message in messages %}
				<div class="alert alert-{{ message.tags }}">
					{{ message }}
				</div>
			{% endfor %}
		{% endif %}

		<table style="font-size: 18px;">
		<tbody>
		<tr>
			<th>ID</th>
			<th>Contest name</th>
			<th>Contest times (UTC)</th>
			<th>Announcement</th>
			<th>Enter</th>
		</tr>
			{% load tz %}
			{% if page_obj %}
				{% for contest in page_obj %}
					{% if contest.visible %}
						<tr>
							<td>{{ contest.id }}</td>
							<td>{{ contest.name }}</td>
							<td>
								<p>Contest window information:</p>
								<p>
									<b>Start:</b>
									<a href="{{ contest.start_time_url }}">{{ contest.start_time }}</a>
								</p>
								<p>
									<b>End:</b>
									<a href="{{ contest.end_time_url }}">{{ contest.end_time }}</a>
								</p>
								<p>
									<b>Time limit:</b> {{ contest.time_limit }} minutes
								</p>
								{% if contest.ended %}
									{% if contest.needs_to_submit and contest.format != "Semicolon" %}
										<p>
											You need to submit within
											<span class="timer" redirect="refresh" current-server-time="{{ current_server_time }}" end-time="{{ contest.submit_end_time|date:"U"}}"></span>
										</p>
									{% else %}
										<p><b>Contest has finished.</b></p>
									{% endif %}
								{% elif contest.started %}
									{% if contest.joined %}
										{% if contest.running %}
										<p>
											Your attempt ends in
											<span class="timer" redirect="refresh" current-server-time="{{ current_server_time }}" end-time="{{ contest.user_end_time|date:"U"}}"></span>
										</p>
										{% else %}
										{% if contest.needs_to_submit and contest.format != "Semicolon" %}
										<p>
											You need to submit within
											<span class="timer" redirect="refresh" current-server-time="{{ current_server_time }}" end-time="{{ contest.submit_end_time|date:"U"}}"></span>
										</p>
										{% else %}
										<p>Your attempt has finished</p>
										<p>
											Contest ends in
											<span class="timer" redirect="refresh" current-server-time="{{ current_server_time }}" end-time="{{ contest.end_time|date:"U"}}"></span>
										</p>
										{% endif %}
										{% endif %}
									{% else %}
										<p>
											Ends in
											<span class="timer" redirect="refresh" current-server-time="{{ current_server_time }}" end-time="{{ contest.end_time|date:"U"}}"></span>
										</p>
									{% endif %}
								{% else %}
									<p>
										Starts in:
										<span class="timer" redirect="refresh" current-server-time="{{ current_server_time }}" end-time="{{ contest.start_time|date:"U"}}"></span>
									</p>
								{% endif %}
							</td>
							<td>
								<a href="{{ contest.announcement_link }}">View</a>
							</td>
							<td>
								{% if contest.ended %}
									{% if contest.contest_format == "Semicolon" %}
										<a href="{% url 'contests-semiarena' contest.id %}" style="color: lightgreen;">Enter contest arena</a>
									{% else %}
										{% if contest.needs_to_submit %}
											<a href="{% url 'contests-submit' contest.id %}" style="color: lightgreen;">Submit contest</a>
										{% else %}
											<a href="{% url 'contests-arena' contest.id %}" style="color: lightgreen;">Enter contest arena</a>
										{% endif %}
									{% endif %}

								{% elif contest.started %}

									{% if contest.joined %}
										{% if contest.contest_format == "Semicolon" %}
											<a href="{% url 'contests-semiarena' contest.id %}" style="color: lightgreen;">Enter contest arena</a>
										{% else %}
											{% if contest.running or not contest.needs_to_submit %}
												<a href="{% url 'contests-arena' contest.id %}" style="color: lightgreen;">Enter contest arena</a>
											{% elif contest.needs_to_submit %}
												<a href="{% url 'contests-submit' contest.id %}" style="color: lightgreen;">Submit contest</a>
											{% endif %}
										{% endif %}
									{% else %}
										<a href="{% url 'contests-confirm' contest.id %}" style="color: lightgreen;">Join the contest</a>
									{% endif %}

								{% endif %}
							</td>
						</tr>
					{% endif %}
				{% endfor %}
			{% endif %}
		</tbody>
		</table>
		
		<div class="pagination">
			{% with ''|center:page_obj.paginator.num_pages as range %}
			{% for i in range %}
				{% if forloop.counter == page_obj.number %}
					<a class="paginationLink paginationSelected" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a>
				{% else %}
					<a class="paginationLink" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a>
				{% endif %}
			{% endfor %}
			{% endwith %}
		</div>
		
		<script type="text/javascript" src="{% static 'js/timers.js' %}"></script>
  	</body>
</html>

contests/templates/contests/semiarena.html
{% load static %}
<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<title>(;) Semicolon Math: {{ contest.name }}</title>
		<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" />
	</head>
	<body style="max-width: 60em !important;">
		<div style="display: flex; justify-content: space-between; align-items: center;">
			<div>
				<h1>(;) Semicolon Math: {{ contest.name }} </h1>
			</div>
			<div style="float: right;">
				{% if user.is_authenticated %}
					<a href="{% url 'profile' %}">{{ user.username }}</a> |
					<a href="{% url 'logout' %}">Logout</a>
				{% else %}
					<a href="{% url 'login' %}?next={{ request.path }}">Login</a> |
					<a href="{% url 'register' %}">Register</a>
				{% endif %}
			</div>
		</div>

		<nav>
			<a href="{% url 'blog-home' %}">Home</a> |
			<a href="{% url 'contests-home' %}">Contests</a> |
			<a href="{% url 'problemset-home' %}">Problemset</a> |
			<a href="{% url 'blog-about' %}">About</a>
		</nav>
		
		<div style="min-width: 550px;">
		<div style="float: right; width: 10em; position: sticky; top: 1em; padding: 1em 1em; border-style: double;">
			{% if contest.running %}
				<div class="timerDiv">
					<h2>
						Time left:
						<span class="timer" redirect="refresh" current-server-time="{{ current_server_time }}" end-time="{{ contest.user_end_time|date:"U" }}"></span>
					</h2>
				</div>
			{% endif %}
			{% if messages %}
				{% for message in messages %}
					<div class="alert alert-{{ message.tags }}">
						{{ message }}
					</div>
				{% endfor %}
			{% endif %}
			<a href="#announcements">Note on announcements</a> /
			{% if contest.has_solutions %}
				<a href="{{ contest.solutions_url }}">View contest solutions</a> /
			{% endif %}
			{% if contest.ended_for_all %}
				<a href="{% url 'contests-scoreboard' contest.id %}">View scoreboard</a> /
			{% elif contest.user_finished_but_running %}
				<p>
					Your attempt has finished, contest ends in:
					<span class="timer" redirect="refresh" current-server-time="{{ current_server_time }}" end-time="{{ contest.end_time|date:"U" }}"></span>
				</p>
			{% endif %}
			{% if contest_problems %}
				{% for contest_problem in contest_problems %}
					{% if contest_problem.solved %}
						<a href="#{{ forloop.counter }}" style="color: lightgreen;">Problem {{ forloop.counter }} (s)</a> /
					{% else %}
						<a href="#{{ forloop.counter }}" style="color: tomato;">Problem {{ forloop.counter }} (u)</a> /
					{% endif %}
				{% endfor %}
				<small><p>
					Note <b>'s'</b> means solved and <b>'u'</b> means unsolved.
				</p></small>
			{% endif %}
		</div>
		

		{% if contest_problems %}
			<div style="margin-right: 13em;">
			<div class="box" id="announcements">
				<h2>Announcements</h2>
				<p>Announcements are available on <a href="https://discord.gg/9deBe7WnEM">our Discord server</a>.</p>
				<p>They will only be regarding technical issues.</p>
				<p>
					We will post fixes to any problems AFTER the contest has finished, to make it fair to everyone.
					The fixes will be available in the problem statements.
				</p>
				<p>
					Tip: After submitting an answer, please wait for at
					least 15 seconds for the website to load and return
					your verdict. DO NOT refresh the page.
				</p>
			</div>

			{% for contest_problem in contest_problems %}
				<div class="box" id="{{ forloop.counter }}">
					<h2>Problem {{ forloop.counter }}: {{ contest_problem.problem.name }}</h2>
					{% if contest_problem.solved %}
						<h3 style="color: lightgreen;">Problem status: solved</h3>
					{% else %}
						<h3 style="color: tomato;">Problem status: not solved</h3>
					{% endif %}
					<h3>Value (if solved during a running contest): {{ contest_problem.value }}</h3>

					<div>{{ contest_problem.problem.content|safe }}</div>

					{% if user.is_authenticated %}
						{% if contest.running and not contest_problem.solved %}
							<form method="POST">
								{% csrf_token %}
								{{ contest_problem.form.as_p }}
								<button type="submit">Submit</button>
							</form>
						{% elif not contest.running %}
							<form method="POST">
								{% csrf_token %}
								{{ contest_problem.form.as_p }}
								<button type="submit">Submit</button>
							</form>
						{% endif %}
					{% else %}
						<div class="alert alert-error">
							Please login before submitting this problem.
						</div>
					{% endif %}
				</div>
			{% endfor %}
			</div>
		{% endif %}
		</div>

		<style>
			#id_problem_id {
				display: none;
			}
		</style>


		<script type="text/javascript" src="{% static 'js/timers.js' %}"></script>
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.4/dist/katex.min.css" integrity="sha384-vKruj+a13U8yHIkAyGgK1J3ArTLzrFGBbBc0tDp4ad/EyewESeXE/Iv67Aj8gKZ0" crossorigin="anonymous">
		<script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.4/dist/katex.min.js" integrity="sha384-PwRUT/YqbnEjkZO0zZxNqcxACrXe+j766U2amXcgMg5457rve2Y7I6ZJSm2A0mS4" crossorigin="anonymous"></script>
		<script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.4/dist/contrib/auto-render.min.js" integrity="sha384-+VBxd3r6XgURycqtZ117nYw44OOcIax56Z4dCRWbxyPt0Koah1uHoK0o4+/RRE05" crossorigin="anonymous"></script>
		<script>
    	document.addEventListener("DOMContentLoaded", function() {
			renderMathInElement(document.body, {
				delimiters: [
					{left: "$$", right: "$$", display: true},
					{left: "$", right: "$", display: false},
  					{left: "\\(", right: "\\)", display: false},
					{left: "\\begin{equation}", right: "\\end{equation}", display: true},
					{left: "\\begin{equation*}", right: "\\end{equation*}", display: true},
					{left: "\\begin{align}", right: "\\end{align}", display: true},
					{left: "\\begin{align*}", right: "\\end{align*}", display: true},
					{left: "\\begin{alignat}", right: "\\end{alignat}", display: true},
					{left: "\\begin{alignat*}", right: "\\end{alignat*}", display: true},
					{left: "\\begin{gather}", right: "\\end{gather}", display: true},
					{left: "\\begin{gathered}", right: "\\end{gathered}", display: true},
					{left: "\\begin{CD}", right: "\\end{CD}", display: true},
					{left: "\\[", right: "\\]", display: true}
				]
			});
 	   	});
		</script>
  	</body>
</html>