blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='blog-home'),
    path('blog/<int:index>/', views.view_post, name='blog-view-post'),
    path('about/', views.about, name='blog-about'),
]

problemset/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='problemset-home'),
    path('<int:index>/', views.problem, name='problemset-view'),
]

semicolon_src/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('contests/', include('contests.urls')),
    path('problemset/', include('problemset.urls')),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
]

problemset/models.py
from django.db import models
from django.utils import timezone

ANSWER_CHOICES = (
    ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('Blank', 'Blank'),
)

class Problem(models.Model):
    name = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    visible = models.BooleanField(default=False)
    multiple_choice = models.BooleanField(default=True)
    correct_answer = models.IntegerField(default=0)
    correct_answer_choice = models.CharField(max_length=5, choices=ANSWER_CHOICES, default='A')
    def __str__(self):
        return self.name

class Submission(models.Model):
    user_id = models.IntegerField(default=0)
    problem_id = models.IntegerField(default=0)
    problem_solved = models.BooleanField(default=False)
    answer_choice_in_contest = models.CharField(max_length=5, choices=ANSWER_CHOICES, default='Blank')
    answer_in_contest = models.IntegerField(default=0)
    solved_in_contest = models.BooleanField(default=False)
    penalty = models.IntegerField(default=0)
    time_solved_in_contest = models.IntegerField(default=0)
    wrong_submissions_in_contest = models.IntegerField(default=0)

problemset/forms.py
from django import forms

class ProblemForm(forms.Form):
    answer = forms.IntegerField(label='Your answer (should be an integer)')
    # id of the form above should be 'your_answer'

class MultipleChoiceForm(forms.Form):
    ANSWER_CHOICES = [
        ('A', 'A'),
        ('B', 'B'),
        ('C', 'C'),
        ('D', 'D'),
        ('E', 'E'),
    ]
    answer = forms.ChoiceField(widget=forms.RadioSelect, choices=ANSWER_CHOICES)

problemset/views.py
from contests.models import ContestProblem
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
from .models import Problem, Submission
from .forms import ProblemForm, MultipleChoiceForm

def home(request):
    problemset = Problem.objects.all().order_by('-id')
    visible_problems = []
    for problem in problemset:
        problem.solved = False

        user_submissions = Submission.objects.filter(
            user_id=request.user.id,
            problem_id=problem.id
        )
        if(len(user_submissions) > 0):
            problem.solved = user_submissions[0].problem_solved
        
        if(problem.visible):
            visible_problems.append(problem)
    
    paginator = Paginator(visible_problems, 25)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj
    }
    return render(request, 'problemset/home.html', context)

def problem(request, index):
    problem = Problem.objects.get(pk=index)
    user_submissions = Submission.objects.filter(
        user_id=request.user.id,
        problem_id=index
    )
    contest_problems = ContestProblem.objects.filter(
        problem=problem
    )

    if(not problem.visible and not request.user.is_superuser):
        return render(request, 'problemset/blocked.html')

    if request.method == 'POST':
        if problem.multiple_choice:
            form = MultipleChoiceForm(request.POST)
        else:
            form = ProblemForm(request.POST)
        
        if form.is_valid():
            user_answer = form.cleaned_data.get('answer')
            problem_solved = (problem.multiple_choice and user_answer == problem.correct_answer_choice)
            problem_solved |= (not problem.multiple_choice and user_answer == problem.correct_answer)

            if(problem_solved):
                messages.success(request, f"You answer {user_answer} is correct!")
            else:
                messages.error(request, f"You answer {user_answer} is wrong!")

            if(len(user_submissions) == 0):
                new_user_submission = Submission(
                    user_id=request.user.id,
                    problem_id=index,
                    problem_solved=problem_solved
                )
                new_user_submission.save()
            elif(problem_solved):
                current_user_submission = user_submissions[0]
                current_user_submission.problem_solved = True
                current_user_submission.save()

        return redirect('/problemset/' + str(index) + '/')

    else:
        if problem.multiple_choice:
            form = MultipleChoiceForm()
        else:
            form = ProblemForm()
    
    problem_solved = len(user_submissions) >= 1 and user_submissions[0].problem_solved
    context = {
        'problem': problem,
        'form': form,
        'problem_solved': problem_solved,
        'contest_problems': contest_problems
    }
    return render(request, 'problemset/problem.html', context)

problemset/templates/problemset/blocked.html
{% load static %}
<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<title>(;) BLOCKED: Semicolon Math Problemset</title>
		<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" />
	</head>
	<body>
		<div style="display: flex; justify-content: space-between; align-items: center;">
			<div>
				<h1>(;) BLOCKED: Semicolon Math Problemset</h1>
			</div>
			<div style="float: right;">
				{% if user.is_authenticated %}
					<a href="{% url 'profile' %}">{{ user.username }}</a> |
					<a href="{% url 'logout' %}">Logout</a>
				{% else %}
					<a href="{% url 'login' %}">Login</a> |
					<a href="{% url 'register' %}">Register</a>
				{% endif %}
			</div>
		</div>
		<nav>
			<a href="{% url 'blog-home' %}">Home</a> |
			<a href="{% url 'contests-home' %}">Contests</a> |
			<a href="{% url 'problemset-home' %}">Problemset</a> |
			<a href="{% url 'blog-about' %}">About</a>
		</nav>
		{% if messages %}
			{% for message in messages %}
				<div class="alert alert-{{ message.tags }}">
					{{ message }}
				</div>
			{% endfor %}
		{% endif %}
		<h2>
			You cannot view this problem!
		</h2>
  	</body>
</html>

problemset/templates/problemset/home.html
{% load static %}
<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<title>(;) Semicolon Math Problemset</title>
		<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" />
	</head>
	<body>
		<div style="display: flex; justify-content: space-between; align-items: center;">
			<div>
				<h1>(;) Semicolon Math Problemset</h1>
			</div>
			<div style="float: right;">
				{% if user.is_authenticated %}
					<a href="{% url 'profile' %}">{{ user.username }}</a> |
					<a href="{% url 'logout' %}">Logout</a>
				{% else %}
					<a href="{% url 'login' %}?next={{ request.path }}">Login</a> |
					<a href="{% url 'register' %}">Register</a>
				{% endif %}
			</div>
		</div>
		<nav>
			<a href="{% url 'blog-home' %}">Home</a> |
			<a href="{% url 'contests-home' %}">Contests</a> |
			<a href="#">Problemset</a> |
			<a href="{% url 'blog-about' %}">About</a>
		</nav>
		{% if messages %}
			{% for message in messages %}
				<div class="alert alert-{{ message.tags }}">
					{{ message }}
				</div>
			{% endfor %}
		{% endif %}
		<table>
			<tbody>
			<tr>
				<th>ID</th>
				<th>Problem Name</th>
				<th>Solved</th>
			</tr>
			{% if page_obj %}
				{% for problem in page_obj %}
					{% if problem.visible %}
					<tr>
						<td>{{ problem.id }}</td>
						<td><a href="{% url 'problemset-view' problem.id %}">{{ problem.name }}</a></td>
						{% if problem.solved %}
							<td style="color: lightgreen;">Solved</td>
						{% else %}
							<td style="color: tomato;">Not solved</td>
						{% endif %}
					</tr>
					{% endif %}
				{% endfor %}
			{% endif %}
			</tbody>
		</table>

		<div class="pagination">
			{% with ''|center:page_obj.paginator.num_pages as range %}
			{% for i in range %}
				{% if forloop.counter == page_obj.number %}
					<a class="paginationLink paginationSelected" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a>
				{% else %}
					<a class="paginationLink" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a>
				{% endif %}
			{% endfor %}
			{% endwith %}
		</div>

  	</body>
</html>

problemset/templates/problemset/problem.html
{% load static %}
<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<title>(;) Semicolon Math: {{ problem.name }}</title>
		<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" />
	</head>
	<body>
		<div style="display: flex; justify-content: space-between; align-items: center;">
			<div>
				<h1>(;) Semicolon Math: {{ problem.name }}</h1>
			</div>
			<div style="float: right;">
				{% if user.is_authenticated %}
					<a href="{% url 'profile' %}">{{ user.username }}</a> |
					<a href="{% url 'logout' %}">Logout</a>
				{% else %}
					<a href="{% url 'login' %}?next={{ request.path }}">Login</a> |
					<a href="{% url 'register' %}">Register</a>
				{% endif %}
			</div>
		</div>
		<nav>
			<a href="{% url 'blog-home' %}">Home</a> |
			<a href="{% url 'contests-home' %}">Contests</a> |
			<a href="{% url 'problemset-home' %}">Problemset</a> |
			<a href="{% url 'blog-about' %}">About</a>
		</nav>
		{% if messages %}
			{% for message in messages %}
				<div class="alert alert-{{ message.tags }}">
					{{ message }}
				</div>
			{% endfor %}
		{% endif %}
		<div class="box">
			<h2>{{ problem.name }} (ID: {{ problem.id }})</h2>
			{% if problem_solved %}
				<h3 style="color: lightgreen;">Problem status: solved</h3>
			{% else %}
				<h3 style="color: tomato;">Problem status: not solved</h3>
			{% endif %}

			<div>{{ problem.content|safe }}</div>
			
			{% if user.is_authenticated %}
				<form method="POST">
					{% csrf_token %}
					{{ form.as_p }}
					{% if problem.multiple_choice %}
						<style>
							#id_answer {
								display: grid;
								grid-template-columns: repeat(5, auto);
								max-width: 350px;
							}
							#id_answer label {
								background-color: skyblue;
								padding: 0.5em;
								border-radius: 0.4em;
								display: inline-block;
								cursor: pointer;
								color: black;
								margin: 0.25em;
							}
							input[type=radio] {
								cursor: pointer;
							}
						</style>
					{% endif %}
					<button type="submit">Submit</button>
				</form>
			{% else %}
				<div class="alert alert-error">
					Please login before submitting this problem.
				</div>
			{% endif %}

			{% if contest_problems|length != 0 %}
				<br/>
				<medium>From these contests:
				{% for contest_problem in contest_problems %}
					{% if contest_problem.contest.contest_format == "Semicolon" %}
						<a href="{% url 'contests-semiarena' contest_problem.contest.id %}">{{ contest_problem.contest.name }}</a> /
					{% else %}
						<a href="{% url 'contests-arena' contest_problem.contest.id %}">{{ contest_problem.contest.name }}</a> /
					{% endif %}
				{% endfor %}
				</medium>
			{% endif %}
		</div>
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.4/dist/katex.min.css" integrity="sha384-vKruj+a13U8yHIkAyGgK1J3ArTLzrFGBbBc0tDp4ad/EyewESeXE/Iv67Aj8gKZ0" crossorigin="anonymous">
		<script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.4/dist/katex.min.js" integrity="sha384-PwRUT/YqbnEjkZO0zZxNqcxACrXe+j766U2amXcgMg5457rve2Y7I6ZJSm2A0mS4" crossorigin="anonymous"></script>
		<script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.4/dist/contrib/auto-render.min.js" integrity="sha384-+VBxd3r6XgURycqtZ117nYw44OOcIax56Z4dCRWbxyPt0Koah1uHoK0o4+/RRE05" crossorigin="anonymous"></script>
		<script>
    	document.addEventListener("DOMContentLoaded", function() {
			renderMathInElement(document.body, {
				delimiters: [
					{left: "$$", right: "$$", display: true},
					{left: "$", right: "$", display: false},
  					{left: "\\(", right: "\\)", display: false},
					{left: "\\begin{equation}", right: "\\end{equation}", display: true},
					{left: "\\begin{equation*}", right: "\\end{equation*}", display: true},
					{left: "\\begin{align}", right: "\\end{align}", display: true},
					{left: "\\begin{align*}", right: "\\end{align*}", display: true},
					{left: "\\begin{alignat}", right: "\\end{alignat}", display: true},
					{left: "\\begin{alignat*}", right: "\\end{alignat*}", display: true},
					{left: "\\begin{gather}", right: "\\end{gather}", display: true},
					{left: "\\begin{gathered}", right: "\\end{gathered}", display: true},
					{left: "\\begin{CD}", right: "\\end{CD}", display: true},
					{left: "\\[", right: "\\]", display: true}
				]
			});
 	   	});
		</script>
  	</body>
</html>